### ISSUE TITLE
Devices are marked as "unavailable" after Home Assistant reboot, instead of as "away".

### ISSUE THREAD

**Issue by MathisP75** [AlexandrErohin/home-assistant-tplink-router#81]
**Describe the bug**
When a device is not present on the network, it should be marked as "away". However, upon restarting Home Assistant, devices are marked as "unavailable" until the device connects to the wifi network again.

**Additional Information (please complete the following information)**
 - Router Hardware Version: Archer AX55 v4.0
 - Router Firmware Version: 1.1.1 Build 20240531 rel.78852(4341)
 - Home Assistant Version: 2024.9.1
 - TP-Link Router Integration Component Version: 1.15.2

**Comment by MDV85** [comment]
Hi. DECO X60 the same problem .....

**Comment by AlexandrErohin** [comment]
After restarting Home Assistant all sensors/device_tracker from all integrations become unavailable until an integration set current state to a sensor. There are a lot of device_trackers can be from several integrations. After restarting Home Assistant the integration doesnt know how many devices connected to the router until the router tells. But the router can tell only active devices - it doesnt tell about all devices which were connected in the past. Since this moment the integration can mark the device as away when this device is no longer on the router list of active devices
